SELECT 
    CAST(id AS INTEGER) AS id,
    "index",
    "Name",
    CAST("Release_Date" AS timestamp) AS "Release_Date",
    "IMDB_URL",
    unknown,
    "Action",
    "Adventure",
    "Animation",
    "Children_s",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    "Film_Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci_Fi",
    "Thriller",
    "War",
    "Western"
FROM {{ source('recommmender_system_raw', 'movie') }}
